export const commonCurrencies = [
    { code: 'USD', name: 'US Dollar', flag: '🇺🇸', symbol: '$' },
    { code: 'EUR', name: 'Euro', flag: '🇪🇺', symbol: '€' },
    { code: 'GBP', name: 'British Pound', flag: '🇬🇧', symbol: '£' },
    { code: 'JPY', name: 'Japanese Yen', flag: '🇯🇵', symbol: '¥' },
    { code: 'AUD', name: 'Australian Dollar', flag: '🇦🇺', symbol: 'A$' },
    { code: 'CAD', name: 'Canadian Dollar', flag: '🇨🇦', symbol: 'C$' },
    { code: 'CHF', name: 'Swiss Franc', flag: '🇨🇭', symbol: 'Fr' },
    { code: 'CNY', name: 'Chinese Yuan', flag: '🇨🇳', symbol: '¥' },
    { code: 'AED', name: 'United Arab Emirates Dirham', flag: '🇦🇪', symbol: 'د.إ' },
    { code: 'AFN', name: 'Afghan Afghani', flag: '🇦🇫', symbol: '؋' },
    { code: 'ALL', name: 'Albanian Lek', flag: '🇦🇱', symbol: 'L' },
    { code: 'AMD', name: 'Armenian Dram', flag: '🇦🇲', symbol: '֏' },
    { code: 'ANG', name: 'Netherlands Antillean Guilder', flag: '🇳🇱', symbol: 'ƒ' },
    { code: 'AOA', name: 'Angolan Kwanza', flag: '🇦🇴', symbol: 'Kz' },
    { code: 'ARS', name: 'Argentine Peso', flag: '🇦🇷', symbol: '$' },
    { code: 'AWG', name: 'Aruban Florin', flag: '🇦🇼', symbol: 'ƒ' },
    { code: 'AZN', name: 'Azerbaijani Manat', flag: '🇦🇿', symbol: '₼' },
    { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', flag: '🇧🇦', symbol: 'KM' },
    { code: 'BBD', name: 'Barbadian Dollar', flag: '🇧🇧', symbol: 'Bds$' },
    { code: 'BDT', name: 'Bangladeshi Taka', flag: '🇧🇩', symbol: '৳' },
    { code: 'BGN', name: 'Bulgarian Lev', flag: '🇧🇬', symbol: 'лв' },
    { code: 'BHD', name: 'Bahraini Dinar', flag: '🇧🇭', symbol: '.د.ب' },
    { code: 'BIF', name: 'Burundian Franc', flag: '🇧🇮', symbol: 'FBu' },
    { code: 'BMD', name: 'Bermudian Dollar', flag: '🇧🇲', symbol: '$' },
    { code: 'BND', name: 'Brunei Dollar', flag: '🇧🇳', symbol: '$' },
    { code: 'BOB', name: 'Bolivian Boliviano', flag: '🇧🇴', symbol: 'Bs' },
    { code: 'BRL', name: 'Brazilian Real', flag: '🇧🇷', symbol: 'R$' },
    { code: 'BSD', name: 'Bahamian Dollar', flag: '🇧🇸', symbol: '$' },
    { code: 'BTN', name: 'Bhutanese Ngultrum', flag: '🇧🇹', symbol: 'Nu.' },
    { code: 'BWP', name: 'Botswana Pula', flag: '🇧🇼', symbol: 'P' },
    { code: 'BYN', name: 'Belarusian Ruble', flag: '🇧🇾', symbol: 'Br' },
    { code: 'BZD', name: 'Belize Dollar', flag: '🇧🇿', symbol: '$' },
    { code: 'CDF', name: 'Congolese Franc', flag: '🇨🇩', symbol: 'FC' },
    { code: 'CLP', name: 'Chilean Peso', flag: '🇨🇱', symbol: '$' },
    { code: 'COP', name: 'Colombian Peso', flag: '🇨🇴', symbol: '$' },
    { code: 'CRC', name: 'Costa Rican Colón', flag: '🇨🇷', symbol: '₡' },
    { code: 'CZK', name: 'Czech Koruna', flag: '🇨🇿', symbol: 'Kč' },
    { code: 'DJF', name: 'Djiboutian Franc', flag: '🇩🇯', symbol: 'Fdj' },
    { code: 'DKK', name: 'Danish Krone', flag: '🇩🇰', symbol: 'kr' },
    { code: 'DOP', name: 'Dominican Peso', flag: '🇩🇴', symbol: 'RD$' },
    { code: 'DZD', name: 'Algerian Dinar', flag: '🇩🇿', symbol: 'دج' },
    { code: 'EGP', name: 'Egyptian Pound', flag: '🇪🇬', symbol: '£' },
    { code: 'ETB', name: 'Ethiopian Birr', flag: '🇪🇹', symbol: 'Br' },
    { code: 'FJD', name: 'Fijian Dollar', flag: '🇫🇯', symbol: 'FJ$' },
    { code: 'GHS', name: 'Ghanaian Cedi', flag: '🇬🇭', symbol: '₵' },
    { code: 'GIP', name: 'Gibraltar Pound', flag: '🇬🇮', symbol: '£' },
    { code: 'GMD', name: 'Gambian Dalasi', flag: '🇬🇲', symbol: 'D' },
    { code: 'GTQ', name: 'Guatemalan Quetzal', flag: '🇬🇹', symbol: 'Q' },
    { code: 'GYD', name: 'Guyanese Dollar', flag: '🇬🇾', symbol: 'G$' },
    { code: 'HKD', name: 'Hong Kong Dollar', flag: '🇭🇰', symbol: 'HK$' },
    { code: 'HNL', name: 'Honduran Lempira', flag: '🇭🇳', symbol: 'L' },
    { code: 'HRK', name: 'Croatian Kuna', flag: '🇭🇷', symbol: 'kn' },
    { code: 'HTG', name: 'Haitian Gourde', flag: '🇭🇹', symbol: 'G' },
    { code: 'HUF', name: 'Hungarian Forint', flag: '🇭🇺', symbol: 'Ft' },
    { code: 'IDR', name: 'Indonesian Rupiah', flag: '🇮🇩', symbol: 'Rp' },
    { code: 'ILS', name: 'Israeli New Shekel', flag: '🇮🇱', symbol: '₪' },
    { code: 'INR', name: 'Indian Rupee', flag: '🇮🇳', symbol: '₹' },
    { code: 'IQD', name: 'Iraqi Dinar', flag: '🇮🇶', symbol: 'ع.د' },
    { code: 'ISK', name: 'Icelandic Króna', flag: '🇮🇸', symbol: 'kr' },
    { code: 'JMD', name: 'Jamaican Dollar', flag: '🇯🇲', symbol: 'J$' },
    { code: 'JOD', name: 'Jordanian Dinar', flag: '🇯🇴', symbol: 'د.ا' },
    { code: 'KES', name: 'Kenyan Shilling', flag: '🇰🇪', symbol: 'KSh' },
    { code: 'KGS', name: 'Kyrgyzstani Som', flag: '🇰🇬', symbol: 'с' },
    { code: 'KHR', name: 'Cambodian Riel', flag: '🇰🇭', symbol: '៛' },
    { code: 'KMF', name: 'Comorian Franc', flag: '🇰🇲', symbol: 'CF' },
    { code: 'KRW', name: 'South Korean Won', flag: '🇰🇷', symbol: '₩' },
    { code: 'KWD', name: 'Kuwaiti Dinar', flag: '🇰🇼', symbol: 'د.ك' },
    { code: 'KYD', name: 'Cayman Islands Dollar', flag: '🇰🇾', symbol: '$' },
    { code: 'KZT', name: 'Kazakhstani Tenge', flag: '🇰🇿', symbol: '₸' },
    { code: 'LAK', name: 'Lao Kip', flag: '🇱🇦', symbol: '₭' },
    { code: 'LBP', name: 'Lebanese Pound', flag: '🇱🇧', symbol: 'ل.ل' },
    { code: 'LKR', name: 'Sri Lankan Rupee', flag: '🇱🇰', symbol: 'Rs' },
    { code: 'LRD', name: 'Liberian Dollar', flag: '🇱🇷', symbol: '$' },
    { code: 'LSL', name: 'Lesotho Loti', flag: '🇱🇸', symbol: 'L' },
];
